name: bbf_app
description: "Bildung und Begegnung Freiburg - offizielle App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  cloud_firestore: ^5.6.12
  flutter_markdown_plus: ^1.0.3
  intl: ^0.20.0
  rive: ^0.13.20
  hijri_calendar: ^1.0.7+7
  dio: ^5.0.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  curved_navigation_bar: ^1.0.6
  flutter_local_notifications: ^19.4.1
  http: ^1.5.0
  timezone: ^0.10.1
  google_maps_flutter: ^2.12.3
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences_android: ^2.4.12
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.10
  table_calendar: ^3.2.0
  file_picker: ^10.3.3
  firebase_storage: ^12.4.10
  flutter_qiblah: ^3.1.0+1
  geolocator: 13.0.4
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.0
  flutter_image_compress: ^2.1.0
  skeletonizer: ^2.1.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "assets/icons/bbf_logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/bbf_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/bbf_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/bbf_logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/qiblah_compass/
    - assets/icons/
    - assets/files/csv_files/
    - assets/files/md_files/project.md
    - assets/files/riv_files/animated_icon_set_-_1_color.riv
    - assets/files/riv_files/springy_animated_icons.riv
    - assets/files/pdf_files/Curriculum_Vitae_Emre.pdf

